- hosts: jenkins_master
  sudo: yes
  vars:
    jenkins_hostname: jenkins.fastfeedback.rocks
  roles:
    - role: liatrio.mount_persist_data
      become: yes
    - role: prereqs
      become: yes
    - role: java_internal
    - role: geerlingguy.git
    - role: geerlingguy.nginx
      ansible_distribution_major_version: 6
      #nginx_upstreams: 
      #  - name: jenkins
      #    servers: {
      #      "127.0.0.1:8080"
      #    }
      nginx_vhosts:
        - listen: "80"
          server_name: "jenkins.fastfeedback.rocks"
          extra_parameters: |
            location / {
              proxy_set_header        Host $host:$server_port;
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        X-Forwarded-Proto $scheme;
              proxy_pass              http://127.0.0.1:8080;
              # Required for new HTTP-based CLI
              proxy_http_version 1.1;
              proxy_request_buffering off;
              proxy_buffering off; # Required for HTTP-based CLI to work over SSL
              add_header 'X-SSH-Endpoint' 'jenkins.fastfeedback.rocks:50022' always;
            }
    - role: geerlingguy.jenkins
      become: true
      jenkins_plugins_state: present
      jenkins_plugins: 
        - blueocean-personalization
        - pipeline-build-step
        - pipeline-model-declarative-agent
        - workflow-cps-global-lib
        - handlebars
        - slack
        - junit
        - git-client
        - blueocean-pipeline-api-impl
        - workflow-basic-steps
        - pipeline-input-step
        - scm-api
        - pipeline-model-api
        - git
        - blueocean-commons
        - jenkins-design-language
        - pipeline-stage-view
        - jquery
        - blueocean-pipeline-editor
        - handy-uri-templates-2-api
        - github
        - blueocean-pipeline-scm-api
        - pubsub-light
        - momentjs
        - script-security
        - workflow-aggregator
        - docker-workflow
        - credentials-binding
        - cloudbees-folder
        - blueocean-jwt
        - pipeline-milestone-step
        - blueocean-core-js
        - jira
        - pipeline-model-extensions
        - favorite
        - workflow-scm-step
        - github-branch-source
        - blueocean
        - pipeline-utility-steps
        - durable-task
        - pipeline-graph-analysis
        - blueocean-web
        - jackson2-api
        - blueocean-rest-impl
        - htmlpublisher
        - blueocean-config
        - matrix-project
        - pipeline-model-definition
        - blueocean-jira
        - blueocean-autofavorite
        - workflow-job
        - config-file-provider
        - docker-commons
        - display-url-api
        - sonar
        - pipeline-stage-tags-metadata
        - apache-httpcomponents-client-4-api
        - workflow-multibranch
        - blueocean-github-pipeline
        - workflow-durable-task-step
        - workflow-api
        - pipeline-stage-step
        - workflow-cps
        - structs
        - blueocean-rest
        - blueocean-git-pipeline
        - mailer
        - bouncycastle-api
        - blueocean-bitbucket-pipeline
        - SSE
        - plain-credentials
        - git-server
        - blueocean-dashboard
        - credentials
        - ace-editor
        - jQuery and jQuery UI
        - blueocean-events
        - cloudbees-bitbucket-branch-source
        - workflow-step-api
        - github-api
        - blueocean-display-url
        - ssh-credentials
        - authentication-tokens
        - workflow-support
        - blueocean-i18n
        - jsch
        - token-macro
        - mercurial
        - pipeline-rest-api
        - branch-api
        - variant
        - job-dsl
  tasks:
  - file:
      path: /var/lib/jenkins/jobs/seedjob/
      state: directory
      owner: jenkins
      group: jenkins
      mode: u+rwx,g+rwx
  - copy:
      src: resources/jobs/seedjob/config.xml
      dest: /var/lib/jenkins/jobs/seedjob/config.xml
      owner: jenkins
      group: jenkins
      mode: u+rwx,g+rwx
