- hosts: jenkins_master
  sudo: yes
  vars:
    jenkins_hostname: 54.219.170.56
  roles:
    - role: java_internal
    - role: jdauphant.ssl-certs
      ssl_certs_path_owner: "ec2-user"
      ssl_certs_path_group: "ec2-user"
      ssl_certs_common_name: "jenkins.fastfeedback.rocks"
      ssl_certs_generate_dh_param: true
    - role: jdauphant.nginx
      nginx_configs:
        upstream:
          - upstream jenkins { server 127.0.0.1:8080 fail_timeout=0; }
        ssl:
          - ssl_certificate_key {{ssl_certs_privkey_path}}
          - ssl_certificate     {{ssl_certs_cert_path}}
          - ssl_dhparam         {{ssl_certs_dhparam_path}}
      nginx_sites:
        jenkins:
        - listen 443 ssl
        - server_name {{jenkins_hostname}}
        - set $myhost {{jenkins_hostname}} 
        - |
          location \ {
            proxy_set_header        Host $host:$server_port;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_redirect http:// https://;
            proxy_pass              http://jenkins;
            # Required for new HTTP-based CLI
            proxy_http_version 1.1;
            proxy_request_buffering off;
            proxy_buffering off; # Required for HTTP-based CLI to work over SSL
            add_header 'X-SSH-Endpoint' 'jenkins.domain.tld:50022' always;
          }
    - role: geerlingguy.jenkins
      become: true
      jenkins_plugins_state: present
      jenkins_plugins: 
        - blueocean-personalization
        - pipeline-build-step
        - pipeline-model-declarative-agent
        - workflow-cps-global-lib
        - handlebars
        - slack
        - junit
        - git-client
        - blueocean-pipeline-api-impl
        - workflow-basic-steps
        - pipeline-input-step
        - scm-api
        - pipeline-model-api
        - git
        - blueocean-commons
        - jenkins-design-language
        - pipeline-stage-view
        - jquery
        - blueocean-pipeline-editor
        - handy-uri-templates-2-api
        - github
        - blueocean-pipeline-scm-api
        - pubsub-light
        - momentjs
        - script-security
        - workflow-aggregator
        - docker-workflow
        - credentials-binding
        - cloudbees-folder
        - blueocean-jwt
        - pipeline-milestone-step
        - blueocean-core-js
        - jira
        - pipeline-model-extensions
        - favorite
        - workflow-scm-step
        - github-branch-source
        - blueocean
        - pipeline-utility-steps
        - durable-task
        - pipeline-graph-analysis
        - blueocean-web
        - jackson2-api
        - blueocean-rest-impl
        - htmlpublisher
        - blueocean-config
        - matrix-project
        - pipeline-model-definition
        - blueocean-jira
        - blueocean-autofavorite
        - workflow-job
        - config-file-provider
        - docker-commons
        - display-url-api
        - sonar
        - pipeline-stage-tags-metadata
        - apache-httpcomponents-client-4-api
        - workflow-multibranch
        - blueocean-github-pipeline
        - workflow-durable-task-step
        - workflow-api
        - pipeline-stage-step
        - workflow-cps
        - structs
        - blueocean-rest
        - blueocean-git-pipeline
        - mailer
        - bouncycastle-api
        - blueocean-bitbucket-pipeline
        - SSE
        - plain-credentials
        - git-server
        - blueocean-dashboard
        - credentials
        - ace-editor
        - jQuery and jQuery UI
        - blueocean-events
        - cloudbees-bitbucket-branch-source
        - workflow-step-api
        - github-api
        - blueocean-display-url
        - ssh-credentials
        - authentication-tokens
        - workflow-support
        - blueocean-i18n
        - jsch
        - token-macro
        - mercurial
        - pipeline-rest-api
        - branch-api
        - variant

