- hosts: jenkins_master
  sudo: yes
  vars:
    jenkins_hostname: jenkins.fastfeedback.rocks
  roles:
    - role: java_internal
    - role: geerlingguy.jenkins
      become: true
      jenkins_plugins: ["credentials:2.1.14","credentials-binding:1.12"]
  
